### ISSUE TITLE
Animated GLB not loading in BabylonReactNative

### ISSUE THREAD

**Issue by RonnieAshlock** [BabylonJS/BabylonNative#339] opened 2020-07-24 17:22 UTC
Scenes will not load on device or emulator:

https://raw.githubusercontent.com/BabylonJS/Assets/master/meshes/alien.glb
https://raw.githubusercontent.com/BabylonJS/Assets/master/meshes/fish.glb
https://raw.githubusercontent.com/RonnieAshlock/TestAssets/master/GLB/ZeroGravity.glb

**Comment by CedricGuillemet** [comment] 2020-07-27 14:07
At least 2 different issues:
- shader compilation (glslang/c++ side) for alien.glb
- missing sampling constants for fish.glb

**Comment by CedricGuillemet** [comment] 2020-07-27 15:02
Fix for fish.glb in babylonjs : https://github.com/BabylonJS/BabylonNative/issues/339
@RonnieAshlock alien.glb is listed twice. Do you have a 3rd .glb to check?

**Comment by CedricGuillemet** [comment] 2020-07-27 15:55
@syntheticmagus It asserts in glslang due to the traversers (it seems). Can you please take a quick look at trying to load alien.glb ?

**Comment by RonnieAshlock** [comment] 2020-07-27 16:38
@CedricGuillemet Thank you for catching that. I updated the list with the third GLB I tested that would not load. Apologies for the error.

**Comment by CedricGuillemet** [comment] 2020-07-27 17:04
https://raw.githubusercontent.com/BabylonJS/Assets/master/meshes/fish.glb
https://raw.githubusercontent.com/RonnieAshlock/TestAssets/master/GLB/ZeroGravity.glb

Related to the same fix in babylonjs regarding sampling modes.

**Comment by syntheticmagus** [comment] 2020-08-01 01:35
Observations on this so far:
- The assert was caused by an unhandled fall-through case in one of the traversers for types that are not considered either vectors or matrices; I have a fix for this in a branch.
- Once this assert is resolved, it reveals another problem with the collision of attribute positions due to there being non-generic attributes which can be placed at positions after `FIRST_GENERIC_ATTRIBUTE_LOCATION`. This is not a complicated problem, but it's not completely clear to me what the right solution to it is; and since I'm pretty sure @bghgary already had this model working in an earlier version of Babylon Native, I want to ask him about it before trying naive things like simply increasing the `FIRST_GENERIC_ATTRIBUTE_LOCATION` variable.
- Once the attribute collision problem is solved, the model still does not render correctly. It loads and it renders _something_, but the animation is clearly not functioning properly as the model's skin appears to fly off and contort before flying back to the correct positioning. This will require further debugging to understand and correct whatever's causing this behavior.

**Comment by Alex-MSFT** [comment] 2020-08-07 21:08
On latest master I am still seeing Alien.glb and fish.glb failing to load correctly on Android.  It appears that the model loads in correctly then hits a debug assert in GLSLang during shader compile.  If I run as release on windows the model loads correctly, so I am guessing this is a false positive assert.

The callstack from an Android debug session when trying to load alien.glb is pasted below.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/27031140/89688335-c80a7f00-d8b6-11ea-8d29-663deb85fe6e.png)

**Comment by syntheticmagus** [comment] 2020-08-11 18:46
I am able to repro. This is a platform-specific edge case that has to do with changing the types of uniforms at compile time; doesn't affect DX, but affects OpenGL targets and would likely impact Metal, too. Investigating how to fix.

**Comment by RonnieAshlock** [comment] 2020-08-28 17:08
Can not get this scene to load in either simulator or on device (Android). Removed the textures to simplify the material and it still fails.

To repro, load the following GLB in the BabylonReactNative demo app:

https://raw.githubusercontent.com/RonnieAshlock/TestAssets/master/GLB/trex_prowl_no_tex.glb

**Comment by Drigax** [comment] 2020-09-17 21:23
Taking a look at our SPIR-V generated shaders for android, we can see the attribute locations are a bit suspect:

```
"#version 310 es

uniform vec4 morphTargetInfluences[2];
uniform mat4 world;
uniform mat4 mBones[8];
uniform mat4 viewProjection;
uniform mat4 view;
uniform mat4 albedoMatrix;
uniform vec4 vAlbedoInfos;
uniform mat4 ambientMatrix;
uniform vec4 vAmbientInfos;
uniform vec4 vReflectivityInfos;
uniform mat4 reflectivityMatrix;
uniform vec4 vBumpInfos;
uniform mat4 bumpMatrix;
uniform vec4 vLightData0;
uniform vec4 vLightDiffuse0;
uniform vec4 vLightSpecular0;
uniform vec4 vLightGround0;

layout(location = 0) in vec3 a_position;
layout(location = 1) in vec3 a_normal;
layout(location = 2) in vec4 a_tangent;
layout(location = 10) in vec2 a_texcoord0;
layout(location = 13) in vec3 position0;
layout(location = 11) in vec3 normal0;
layout(location = 15) in vec3 tangent0;
layout(location = 14) in vec3 position1;
layout(location = 12) in vec3 normal1;
layout(location = 16) in vec3 tangent1;
layout(location = 8) in vec4 a_indices;
layout(location = 9) in vec4 a_weight;
out vec3 vPositionW;
out vec3 vNormalW;
out vec2 vMainUV1;
out mat3 vTBN;
out vec4 vColor;
layout(location = 4) in vec4 a_color0;

void main()
{
    vec3 positionUpdated = a_position;
    vec3 normalUpdated = a_normal;
    vec4 tangentUpdated = a_tangent;
    vec2 uvUpdated = a_texcoord0;
    positionUpdated += ((position0 - a_position) * morphTargetInfluences[0].x);
    normalUpdated += ((normal0 - a_normal) * morphTargetInfluences[0].x);
    vec3 _67 = tangentUpdated.xyz + ((tangent0 - a_tangent.xyz) * morphTargetInfluences[0].x);
    tangentUpdated = vec4(_67.x, _67.y, _67.z, tangentUpdated.w);
    positionUpdated += ((position1 - a_position) * morphTargetInfluences[1].x);
    normalUpdated += ((normal1 - a_normal) * morphTargetInfluences[1].x);
    vec3 _102 = tangentUpdated.xyz + ((tangent1 - a_tangent.xyz) * morphTargetInfluences[1].x);
    tangentUpdated = vec4(_102.x, _102.y, _102.z, tangentUpdated.w);
    mat4 finalWorld = world;
    mat4 influence = mBones[int(a_indices.x)] * a_weight.x;
    mat4 _136 = mBones[int(a_indices.y)] * a_weight.y;
    influence = mat4(influence[0] + _136[0], influence[1] + _136[1], influence[2] + _136[2], influence[3] + _136[3]);
    mat4 _158 = mBones[int(a_indices.z)] * a_weight.z;
    influence = mat4(influence[0] + _158[0], influence[1] + _158[1], influence[2] + _158[2], influence[3] + _158[3]);
    mat4 _181 = mBones[int(a_indices.w)] * a_weight.w;
    influence = mat4(influence[0] + _181[0], influence[1] + _181[1], influence[2] + _181[2], influence[3] + _181[3]);
    finalWorld = finalWorld * influence;
    vec4 worldPos = finalWorld * vec4(positionUpdated, 1.0);
    vPositionW = vec3(worldPos.xyz);
    mat3 normalWorld = mat3(finalWorld[0].xyz, finalWorld[1].xyz, finalWorld[2].xyz);
    vNormalW = normalize(normalWorld * normalUpdated);
    gl_Position = viewProjection * worldPos;
    vec2 uv2 = vec2(0.0);
    vMainUV1 = uvUpdated;
    vec3 tbnNormal = normalize(normalUpdated);
    vec3 tbnTangent = normalize(tangentUpdated.xyz);
    vec3 tbnBitangent = cross(tbnNormal, tbnTangent) * tangentUpdated.w;
    vTBN = mat3(finalWorld[0].xyz, finalWorld[1].xyz, finalWorld[2].xyz) * mat3(vec3(tbnTangent), vec3(tbnBitangent), vec3(tbnNormal));
    vColor = a_color0;
}

"
```

Where we are skipping locations 3-7, and violating what gl is expecting by using index 16, causing shader compilation to fail, and BGFX subsequently throwing an assert:
https://github.com/bkaradzic/bgfx/blob/master/src/renderer_gl.cpp#L6443-L6466

Definitely something we're doing in the traversers. I'll investigate how we're parsing our attributes to get a good idea of what's happening to our location assignment.

**Comment by Drigax** [comment] 2020-10-19 19:30
Current //TODOs:

[ ] investigate OpenGL attribute slot assignment using the alternate codepath, are our attributes getting the expected slots assigned?
[ ] test changes to attribute assignment on Metal platforms (iOS)
[ ] add documentation to ShaderTraversers::getVertexVaryingsAndLocations to explain the change and why it was needed.

**Comment by Drigax** [comment] 2020-10-29 21:46
Currently pr #450 addresses the crashing associated with loading Alien.glb, and allows ZeroGravity.glb to load properly as well. Fish.glb is **not** a valid glb, with a few thousand errors related to skinning weights, which may explain why it currently fails to render in OpenGL.

**Closed** 2020-11-06 18:05 UTC
