### ISSUE TITLE
Missing WebAudio support

### ISSUE THREAD

**Issue by tymlipari** [BabylonJS/BabylonNative#615] opened 2021-02-19 18:28 UTC
Babylon Native is missing a polyfill for WebAudio to support audio scenarios (including spatial audio).

**Comment by bghgary** [comment] 2021-02-22 20:57
May be a dupe of #31

**Comment by bghgary** [comment] 2021-02-23 18:21
Closing as dupe of #31.

**Closed by bghgary** 2021-02-23 18:21 UTC
