### ISSUE TITLE
[Canvas] Texture Copy & threading

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#809] opened 2021-06-22 09:12 UTC
Because of threading, Canvas rendering has to be done like this:

https://github.com/BabylonJS/BabylonNative/blob/c00b503d3ab4c2809f1d0725e4bc3aa425677aad/Polyfills/Canvas/Source/Context.cpp#L534

In BabylonJS, the texture copy happens just after canvas rendering. In NativeEngine, if the texture copy happens in sync, it will be performed before the canvas rendering. Texture copy has be be done the same way as canvas rendering with tasks pushed on `m_graphicsImpl.BeforeRenderScheduler()`. 

Is there a way to improve this convoluted code?
Is it possible to skip the texture copy and render the canvas to the raw texture instead ?

**Comment by syntheticmagus** [comment] 2021-07-08 20:56
#821 discusses one possible way to address this, among other considerations.

**Comment by bghgary** [comment] 2022-01-11 19:52
Related: #969

**Comment by bghgary** [comment] 2022-12-08 19:12
Duplicate of #969

**Closed by bghgary** 2022-12-08 19:12 UTC
Labels: rendering
