### ISSUE TITLE
Compilation error in UrlRequest_Unix.cpp, Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by giraphics** [BabylonJS/BabylonNative#1195] opened 2023-01-11 07:00 UTC
**Bug**
Following the BabylonNative build steps for Ubuntu, I am getting the following error while executing the `ninja` command.

**To Reproduce**
1. git clone --recursive https://github.com/BabylonJS/BabylonNative.git
2. cd BabylonNative/Apps/
3. npm install
4. cd ..
5. mkdir build
6. cd build
7. sudo apt-get install libgl1-mesa-dev libcurl4-openssl-dev clang-9 libc++-9-dev libc++abi-9-dev lld-9 ninja-build
8. sudo apt-get install libjavascriptcoregtk-4.0-dev
9. cmake -G Ninja -D JSCORE_LIBRARY=/usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so -D NAPI_JAVASCRIPT_ENGINE=JavaScriptCore ..
10. sudo apt-get install libv8-dev
11. cmake -G Ninja -D NAPI_JAVASCRIPT_ENGINE=V8
12. ninja
15. See error:

`[19/152] Building CXX object Dependencies/UrlLib/CMakeFiles/UrlLib.dir/Source/UrlRequest_Unix.cpp.o
FAILED: Dependencies/UrlLib/CMakeFiles/UrlLib.dir/Source/UrlRequest_Unix.cpp.o 
/usr/bin/g++  -I/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Include -I/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source -I/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/arcana.cpp/Source/Submodules/GSL/include -I/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/arcana.cpp/Source/Shared -I/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/arcana.cpp/Source/Unix -Wall -Wextra -Wpedantic -Werror -std=gnu++17 -MD -MT Dependencies/UrlLib/CMakeFiles/UrlLib.dir/Source/UrlRequest_Unix.cpp.o -MF Dependencies/UrlLib/CMakeFiles/UrlLib.dir/Source/UrlRequest_Unix.cpp.o.d -o Dependencies/UrlLib/CMakeFiles/UrlLib.dir/Source/UrlRequest_Unix.cpp.o -c /media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp
/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp: In function ‘void {anonymous}::curl_check(CURLcode)’:
/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp:15:109: error: ‘class std::basic_ostream<char>’ has no member named ‘str’
   15 |             throw std::runtime_error{(std::stringstream{} << "CURL call failed with code (" << code << ")").str()};
      |                                                                                                             ^~~
/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp:15:114: error: no matching function for call to ‘std::runtime_error::runtime_error(<brace-enclosed initializer list>)’
   15 |             throw std::runtime_error{(std::stringstream{} << "CURL call failed with code (" << code << ")").str()};
      |                                                                                                                  ^
In file included from /usr/include/c++/9/array:39,
                 from /usr/include/c++/9/tuple:39,
                 from /usr/include/c++/9/bits/unique_ptr.h:37,
                 from /usr/include/c++/9/memory:80,
                 from /media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Include/UrlLib/UrlLib.h:3,
                 from /media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Base.h:3,
                 from /media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp:1:
/usr/include/c++/9/stdexcept:237:5: note: candidate: ‘std::runtime_error::runtime_error(const std::runtime_error&)’
  237 |     runtime_error(const runtime_error&) _GLIBCXX_NOTHROW;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:237:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/9/stdexcept:232:5: note: candidate: ‘std::runtime_error::runtime_error(std::runtime_error&&)’
  232 |     runtime_error(runtime_error&&) noexcept;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:232:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/9/stdexcept:230:5: note: candidate: ‘std::runtime_error::runtime_error(const char*)’
  230 |     runtime_error(const char*) _GLIBCXX_TXN_SAFE;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:230:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/9/stdexcept:226:5: note: candidate: ‘std::runtime_error::runtime_error(const string&)’
  226 |     runtime_error(const string& __arg) _GLIBCXX_TXN_SAFE;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:226:5: note:   conversion of argument 1 would be ill-formed:
/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp: In function ‘void {anonymous}::curl_check(CURLUcode)’:
/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp:23:110: error: ‘class std::basic_ostream<char>’ has no member named ‘str’
   23 |             throw std::runtime_error{(std::stringstream{} << "CURLU call failed with code (" << code << ")").str()};
      |                                                                                                              ^~~
/media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp:23:115: error: no matching function for call to ‘std::runtime_error::runtime_error(<brace-enclosed initializer list>)’
   23 |             throw std::runtime_error{(std::stringstream{} << "CURLU call failed with code (" << code << ")").str()};
      |                                                                                                                   ^
In file included from /usr/include/c++/9/array:39,
                 from /usr/include/c++/9/tuple:39,
                 from /usr/include/c++/9/bits/unique_ptr.h:37,
                 from /usr/include/c++/9/memory:80,
                 from /media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Include/UrlLib/UrlLib.h:3,
                 from /media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Base.h:3,
                 from /media/parminder.singh/aux_2tb/gfx/nativewiz/BabylonNativeSrc4/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp:1:
/usr/include/c++/9/stdexcept:237:5: note: candidate: ‘std::runtime_error::runtime_error(const std::runtime_error&)’
  237 |     runtime_error(const runtime_error&) _GLIBCXX_NOTHROW;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:237:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/9/stdexcept:232:5: note: candidate: ‘std::runtime_error::runtime_error(std::runtime_error&&)’
  232 |     runtime_error(runtime_error&&) noexcept;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:232:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/9/stdexcept:230:5: note: candidate: ‘std::runtime_error::runtime_error(const char*)’
  230 |     runtime_error(const char*) _GLIBCXX_TXN_SAFE;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:230:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/9/stdexcept:226:5: note: candidate: ‘std::runtime_error::runtime_error(const string&)’
  226 |     runtime_error(const string& __arg) _GLIBCXX_TXN_SAFE;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:226:5: note:   conversion of argument 1 would be ill-formed:
[36/152] Building CXX object Plugins/NativeEngine/CMakeFiles/NativeEngine.dir/Source/NativeEngine.cpp.o
ninja: build stopped: subcommand [failed.`]

[build_log.zip](https://github.com/BabylonJS/BabylonNative/files/10389578/build_log.zip)

**Comment by bghgary** [comment] 2023-01-18 21:05
Hmm, it looks like I'm using a syntax that the older compiler doesn't like. Can you see if you can figure out what the issue is? We don't build with the older Ubuntu LTS anymore in our CI and I don't have one readily available now.

Another option would be to update to Ubuntu 22.

**Comment by bghgary** [comment] 2023-01-26 19:40
Closing for now. Please reopen if you need more support or better yet use the forum.

**Closed by bghgary** 2023-01-26 19:40 UTC
