### ISSUE TITLE
Need a way to cache shader IL to avoid compilation slowdowns at runtime

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#777] opened 2021-06-04 17:03 UTC
**Is your feature request related to a problem? Please describe.**
Currently, when we load in new shaders from Babylon.js, we have stuttered performance with the shader getting parsed and compiled at runtime.

**Describe the solution you'd like**
It would be nice to find a way for us to be able to package pre-compiled intermediate language binaries with our applications so we don't need to recompile at runtime when we already know what our target platform will be.

**Comment by bghgary** [comment] 2024-09-05 22:38
Dupe of #1407

**Closed by bghgary** 2024-09-05 22:38 UTC
Labels: performance
