### ISSUE TITLE
Native XR objects should minimize communication over NAPI

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#910] opened 2021-10-06 20:54 UTC
We currently have a lot of objects in NativeXr that use `InstanceAccessor`'s to retrieve static information known at construction time, which is much slower than planting the data on the JS-side object and letting JS retrieve it from there.

`XRPose`, for example, is a transform only valid during the frame when it's generated, so we can turn its "transform" property from an `InstanceAccessor` into an `InstanceValue`, similarly to this suggestion for `PointerEvent`: https://github.com/BabylonJS/BabylonNative/pull/909#discussion_r723610642

Types I'm looking to refactor:
- [ ] `XRRigidTransform`
  - `position`
  - `orientation`
  - `matrix`
- [ ] `XRWebGLLayer`
  - `getViewport`
- [ ] `XRView`
  - `eye`
  - `projectionMatrix`
  - `transform`
  - `isFirstPersonObserver`
- [ ] `XRViewerPose`
  - `transform`
  - `views`
  - `emulatedPosition`
- [ ] `XRPose`
  - `transform`
- [ ] `XRRay`
  - `origin`
  - `direction`
  - `matrix`
- [ ] `XRPlane`
  - `polygon`
  - `lastChangedTime`
  - `parentSceneObject`
- [ ] `XRMesh`
  - `position`
  - `indices`
  - `normals`
  - `lastChangedTime`
  - `parentSceneObject`
- [ ] `XRFrame`
  - `getViewerPose`
  - `trackedAnchors`
  - `worldInformation`
  - `featurePointCloud`
  - `updatePlanes`
  - `updateMeshes`
  - `updateAnchors`
- [ ] `XRSession`
  - `inputSources`
  - `ProcessEyeInputSource`
  - `ProcessControllerInputSources`

**Comment by bghgary** [comment] 2024-09-09 22:47
More or less a dupe of #1010.

**Closed by bghgary** 2024-09-09 22:47 UTC
