### ISSUE TITLE
Update the engine features with the right value

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/BabylonNative#553] opened 2020-12-22 08:49 UTC
From an email sent to Gary:

I forgot to say when merging the WebGPU changes to the master branch that I added a new `EngineFeature` property to the engine, which basically replaces all the occurrences of `engine.webGLVersion` that were used for testing purposes by a test in the feature property. For the time being, all the features are `false` for native engine as I didn't know what the right value would be.

So, that's something you (or someone else in the Native team) will need to update to match the capabilities of the engine. There's a comment for each capability in the engineFeatures.ts file, but feel tree to ask me if something is not clear.

**Comment by bghgary** [comment] 2022-04-21 18:49
This is to correctly set the engine._caps from the native side.

**Comment by bghgary** [comment] 2024-09-05 23:26
This is similar and basically a dupe of #1163

**Closed by bghgary** 2024-09-05 23:26 UTC
Labels: rendering
